### ISSUE TITLE
训练的loss一直不下降

### ISSUE THREAD

**Issue by tanhao-call** [syc11-25/PAPIF#2]
作者您好，我最近在复现一些偏振融合的文章，在复现您的文章的时候，发现按照您在论文中写的，下载RGB图像集，把图片分割成40*40的小块之后，发现得到的图像看起来很暗。我用这样的图像去训练发现整个100轮，loss都没有下降过，最后用完整的一幅图像去测试的时候也发现得到的融合图像亮度很低。并且我在您给出的代码中没有看到您像论文中说的那样使用rgb转ycrcb，是否是因为给出的代码是训练灰度图像的原因？但loss中的lambda又是10。感觉有点不清楚

**Comment by syc11-25** [comment]
您好，上传的代码是样例代码，可以直接训练灰度图像，但是需要修改一下损失函数的权重；也可以训练彩色图像，其中rgb转ycrcb的函数在util文件中，可以直接调用，需要自己修改一下代码。

**Comment by tanhao-call** [comment]
非常感谢您的回答，祝您身体健康，万事如意。，
我现在想要测试RGB图像输入到模型中得到的结果是怎样的，但代码中的Ycrcb转rgb的函数我有点不太会写，报错提醒我说有4个dim,不等于3个。或者就是输出的都是绿色通道的。想问问您方便把您的这个代码上传到github上让我学习一下吗？

**Comment by syc11-25** [comment]
原有的代码已经找不到了，我回头写一下，再上传代码。

**Comment by tanhao-call** [comment]
好的，非常感谢您。

**Comment by syc11-25** [comment]
已经更新了RGB版本的代码，欢迎参考。

**Comment by 225ceV** [comment]
题主您好，您后来解决了训练的问题吗？我用了最新的RGB版本的代码，但是依然遇到了不收敛和亮度低的问题。不知道是否需要改动代码中的超参数和损失函数。这是我的邮箱jiakun_jin@163.com

**Comment by tanhao-call** [comment]
抱歉因为时间比较久了，我已经不太记得当时是如何解决的这个问题的了，然后后面使用了新的一个数据集进行训练，好像效果不太好，然后就没有再使用这个方法去训练了，只是用已有的模型进行测试然后作为一个比对样本了

**Comment by 225ceV** [comment]
好吧，感谢
