### ISSUE TITLE
损失函数写得有问题

### ISSUE THREAD

**Issue by tanhao-call** [syc11-25/PAPIF#3]
我认真看了一下您的损失函数，和您在论文中提出的好像不太一样，对于r下标为w，上标为s的这个参数，似乎并没有定义一个g(x)=max(x,0.0001)来进行计算，而是直接使用sigma1/(sigma1+sigma2+0.0000001)来计算，想问问这里面是有什么化简的步骤吗？还是说在某种程度上来说是等价的？

还有另外一个问题是，我很想找到您当时训练灰度图像的数据集来训练一下，但您在文章中只是说是从PFNet论文中获得的100对，我看了一下那篇文章，作者好像没有给出一个下载地址，然后所用的灰度图像对数也是215对，方便问一下您方便将数据发一下吗？

**Comment by syc11-25** [comment]
感谢对本工作的关注，您的分析是有道理的，g(x)的作用就是防止出现一些除0错误，因此可以通过化简和近似，在具体计算时在分母增加0.0000001来实现同样的作用。
关于第二个问题，数据使用可能涉及到一些授权问题等，可能还需要找对应的作者要数据。
