### ISSUE TITLE
about dataset 

### ISSUE THREAD

**Issue by ccatian** [syc11-25/PAPIF#5]
作者您好，在文章中提到的“we calculate DoLP of the three channels of RGB image, respectively, and concatenate them together to obtain a color DoLP” 请问可以提供此处的计算彩色DoLP的相关代码嘛？非常感谢！

**Comment by syc11-25** [comment]
您好，您可以按照计算灰度图像的方式分别计算RGB图像的三个通道，然后得到RGB个通道自己的DoLP，再沿通道维度进行拼接即可。
