### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by ccatian** [syc11-25/PAPIF#6]

**Comment by ccatian** [comment]
作者您好，在训练过程中，若将batch size改为8，则运行train_rgb.py这个文件得到的损失几乎没有任何变化，若修改batch size为16或者更大，则会出现 CUDA out of memory(使用48G和80G的gpu都会出现这种问题)，请问这种情况怎么解决呢？

**Comment by syc11-25** [comment]
您好，在训练的时候batchsize是对裁剪后的图像块而言的，直接使用整张图像的话，可能会占用较大的显存。

**Comment by ccatian** [comment]
感谢您的指导，是在阅读文章的时候疏忽了，但是我看您给的源代码里好像没有包含对整张图像进行裁剪的部分，所以是需要自己编写对源图像裁剪的代码吗？此外，裁剪之后应该会有很多的图像块，应该怎么保存呢？（或者说保存为什么类型的文件？）最后，方便添加一个您的联系方式吗？目前我的研究方向是偏振图像融合，希望后续的学习中能向您多多请教，非常抱歉打扰您了。





------------------ Original ------------------
From: syc11-25 ***@***.***&gt;
Date: Tue,Aug 20,2024 11:04 AM
To: syc11-25/PAPIF ***@***.***&gt;
Cc: ccatian ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [syc11-25/PAPIF] about train (Issue #6)





 
您好，在训练的时候batchsize是对裁剪后的图像块而言的，直接使用整张图像的话，可能会占用较大的显存。

**Comment by syc11-25** [comment]
对的，自己需要对数据进行剪裁预处理，保存方式可以保存为图片，保存为其他格式需要自己重写dataloader。有问题的话在这里问，我都会尽力回答的。
